export const SET_VALIDATION = 'SET_VALIDATION';
export const REMOVE_VALIDATION = 'REMOVE_VALIDATION';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const USER_LOADED = 'USER_LOADED';
export const REGISTER_FAILED = 'REGISTER_FAILED'
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const LOGOUT = 'LOGOUT'
export const GET_PROFILES = 'GET_PROFILES'
export const PROFILE_ERROR = 'PROFILE_ERROR'


    